name: Rust

on:
  push:
    branches: [ "development", "zero-to-prod" ]
  pull_request:
    branches: [ "development" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Test
      run: cargo test
    - name: Coverage
      run: |
        rustup component add llvm-tools-preview
        cargo install cargo-llvm-cov
        cargo llvm-cov
    - name: Linting
      run: |
        rustup component add clippy
        cargo clippy -- -D warnings
    - name: Formatting
      run: |
        rustup component add rustfmt
        cargo fmt -- --check
    - name: Audit
      run: |
        cargo install cargo-audit
        cargo audit
